import React from 'react';

function BalancedDietArticle() {
  return (
    <div>
       <h1>Eating a balanced diet</h1>
        <div>
        <p><b>Eating a healthy, balanced diet is an important part of maintaining good health, and can help you feel your best.</b></p><p>This means eating a wide variety of foods in the right proportions, and consuming the right amount of food and drink to achieve and maintain a healthy body weight.</p><p>This page covers healthy eating advice for the general population.</p><p>People with special dietary needs or a medical condition should ask their doctor or a registered dietitian for advice.</p>
        <p></p><h2>Food groups in your diet</h2><p><a href="/live-well/eat-well/food-guidelines-and-food-labels/the-eatwell-guide/">The Eatwell Guide</a> shows that to have a healthy, balanced diet, people should try to:</p><ul><li>eat at least 5 portions of a variety of fruit and vegetables every day (see <a href="https://www.nhs.uk/live-well/eat-well/5-a-day-what-counts/">5 A Day</a>)</li><li>base meals on higher fibre starchy foods like potatoes, bread, rice or pasta</li><li>have some dairy or dairy alternatives (such as soya drinks)</li><li>eat some beans, pulses, fish, eggs, meat and other protein</li><li>choose unsaturated oils and spreads, and eat them in small amounts</li><li><a href="/live-well/eat-well/food-guidelines-and-food-labels/water-drinks-nutrition/">drink plenty of fluids</a> (at least 6 to 8 glasses a day)</li></ul><p>If you're having foods and drinks that are high in fat, salt and sugar, have these less often and in small amounts.</p><p>Try to choose a variety of different foods from the 5 main food groups to get a wide range of nutrients.</p><p>Most people in the UK eat and drink too many calories, too much saturated fat, sugar and salt, and not enough fruit, vegetables, oily fish or <a href="/live-well/eat-well/digestive-health/how-to-get-more-fibre-into-your-diet/">fibre</a>.</p><p>The Eatwell Guide does not apply to children under the age of 2 because they have different nutritional needs.</p><p>Between the ages of 2 and 5 years, children should gradually move to eating the same foods as the rest of the family in the proportions shown in the Eatwell Guide.</p><p></p><p></p>
        <p>Fruit and vegetables are a good source of <a href="https://www.nhs.uk/conditions/vitamins-and-minerals/">vitamins and minerals</a> and fibre, and should make up just over a third of the food you eat each day.</p><p>It's recommended that you eat at least 5 portions of a variety of fruit and vegetables every day. They can be fresh, frozen, canned, dried or juiced.</p><p>There's evidence that people who eat at least 5 portions of fruit and vegetables a day have a lower risk of heart disease, stroke and some cancers.</p><p>Eating 5 portions is not as hard as it sounds.</p><p>A portion is:</p><ul><li>80g of fresh, canned or frozen fruit and vegetables</li><li>30g of dried fruit – which should be kept to mealtimes</li><li>150ml glass of fruit juice or smoothie – but do not have more than 1 portion a day as these drinks are sugary and can damage teeth</li></ul><p>Just 1 apple, banana, pear or similar-sized fruit is 1 portion each.</p><p>A slice of pineapple or melon is also 1 portion, and 3 heaped tablespoons of vegetables is another portion.</p><p>Adding a tablespoon of dried fruit, such as raisins, to your morning cereal is an easy way to get 1 portion.</p><p>You could also swap your mid-morning biscuit for a banana, and add a side salad to your lunch. </p><p>In the evening, have a portion of vegetables with dinner and fresh fruit with plain, lower fat yoghurt for dessert to reach your 5 A Day. </p><p><a href="/live-well/eat-well/5-a-day/5-a-day-what-counts/">Find out more about what counts towards your 5 A Day</a></p>
        <p>Starchy foods should make up just over a third of everything you eat. This means your meals should be based on these foods.</p><p>Choose wholegrain or wholemeal varieties of starchy foods, such as brown rice, wholewheat pasta, and brown, wholemeal or higher fibre white bread.</p><p>They contain more fibre, and usually more vitamins and minerals, than white varieties.</p><p>Potatoes with the skins on are a great source of fibre and vitamins. For example, when having boiled potatoes or a jacket potato, eat the skin too.</p><p><a href="/live-well/eat-well/food-types/starchy-foods-and-carbohydrates/">Find out more about starchy foods</a></p>
        <p>Milk and dairy foods, such as cheese and yoghurt, are good sources of protein. They also contain calcium, which helps keep your bones healthy.</p><p>Go for lower fat and lower sugar products where possible.</p><p>Choose semi-skimmed, 1% fat or skimmed milk, as well as lower fat hard cheeses or cottage cheese, and lower fat, lower sugar yoghurt.</p><p>Dairy alternatives, such as soya drinks, are also included in this food group.</p><p>When buying alternatives, choose unsweetened, calcium-fortified versions.</p><p><a href="/live-well/eat-well/food-types/milk-and-dairy-nutrition/">Find out more about milk and dairy foods</a></p>
        <p>These foods are all good sources of protein, which is essential for the body to grow and repair itself.</p><p>They're also good sources of a range of vitamins and minerals.</p><p>Meat is a good source of protein, vitamins and minerals, including iron, zinc and B vitamins. It's also one of the main sources of vitamin B12.</p><p>Choose lean cuts of meat and skinless poultry whenever possible to cut down on fat. Always cook meat thoroughly.</p><p>Try to eat less red and processed meat like bacon, ham and sausages.</p><p><a href="/live-well/eat-well/food-types/meat-nutrition/">Find out more about including meat in your diet</a></p><p>Eggs and fish are also good sources of protein, and contain many vitamins and minerals. Oily fish is particularly rich in omega-3 fatty acids.</p><p>Aim to eat at least 2 portions of fish a week, including 1 portion of oily fish.</p><p>You can choose from fresh, frozen or canned, but remember that canned and smoked fish can often be high in salt.</p><p>Pulses, including beans, peas and lentils, are naturally very low in fat and high in fibre, protein, vitamins and minerals.</p><p>Nuts are high in fibre, and unsalted nuts make a good snack. But they do still contain high levels of fat, so eat them in moderation.</p>
        <p>Some fat in the diet is essential, but on average people in the UK eat too much saturated fat.</p><p>It's important to get most of your fat from unsaturated oils and spreads.</p><p>Swapping to unsaturated fats can help <a href="https://www.nhs.uk/live-well/healthy-body/lower-your-cholesterol/">lower cholesterol</a>.</p><p>Remember that all types of fat are high in energy and should be eaten in small amounts.</p><p><a href="/live-well/eat-well/food-types/different-fats-nutrition/">Find out more about the different types of fats</a></p>
        <p>Too much saturated fat can increase the amount of cholesterol in the blood, which increases your risk of developing <a href="https://www.nhs.uk/conditions/coronary-heart-disease/">heart disease</a>.</p><p>Regularly consuming foods and drinks high in sugar increases your risk of <a href="https://www.nhs.uk/conditions/obesity/">obesity</a> and <a href="https://www.nhs.uk/conditions/tooth-decay/">tooth decay</a>.</p><p>Eating too much salt can raise your blood pressure, which increases your risk of getting heart disease or having a stroke.</p><p>See <a href="/live-well/eat-well/how-to-eat-a-balanced-diet/eight-tips-for-healthy-eating/">8 tips for healthy eating</a> to find out more about why you need to cut down on saturated fat, sugar and salt, which foods they're found in, and how to make healthier choices.</p><p><a href="/live-well/eat-well/how-to-eat-a-balanced-diet/eat-less-saturated-fat/">Find out more about how to eat less saturated fat</a></p>
        <p>Most adults in England are overweight or obese. Check whether you're a healthy weight using the <a href="/live-well/healthy-weight/bmi-calculator/">BMI calculator</a>.</p><p>If you need to lose weight, you can use the <a href="https://www.nhs.uk/better-health/lose-weight/">NHS weight loss plan</a>. It's a free 12-week diet and exercise plan to help you lose weight and develop healthier habits. It has been designed to help you lose weight safely, and keep it off.</p>
        </div>
    </div>
  );
}

export default BalancedDietArticle;