import React from 'react';

function BenefitsExerciseArticle() {
  return (
    <div>
       <h1>Benefits of exercise</h1>
        <div>
          <p><b>Step right up! It's the miracle cure we've all been waiting for.</b></p><p>It can reduce your risk of major illnesses, such as <a href="/conditions/coronary-heart-disease/">coronary heart disease</a>, <a href="/conditions/stroke/">stroke</a>, <a href="/conditions/type-2-diabetes/">type 2 diabetes</a> and <a href="/conditions/cancer/">cancer</a> and lower your risk of early death by up to 30%.</p><p>It's free, easy to take, has an immediate effect and you don't need a GP to get some. Its name? Exercise.</p><p>Check physical activity guidelines for:</p><ul><li><a href="/live-well/exercise/physical-activity-guidelines-children-under-five-years/">children (under 5 years)</a></li><li><a href="/live-well/exercise/physical-activity-guidelines-children-and-young-people/">children and young people (5 to 18 years)</a></li><li><a href="/live-well/exercise/physical-activity-guidelines-for-adults-aged-19-to-64/">exercise (adults 19 to 64 years)</a></li><li><a href="/live-well/exercise/physical-activity-guidelines-older-adults/">older adults (65 years and over)</a></li></ul><p>Exercise is the miracle cure we've always had, but for too long we've neglected to take our recommended dose. Our health is now suffering as a consequence.</p><p>This is no snake oil. Whatever your age, there's strong scientific evidence that being physically active can help you lead a healthier and happier life.</p><p>People who exercise regularly have a lower risk of developing many long-term (chronic) conditions, such as heart disease, type 2 diabetes, stroke, and some cancers.</p><p>Research shows that physical activity can also boost self-esteem, mood, sleep quality and energy, as well as reducing your risk of <a href="/conditions/stress-anxiety-depression/understanding-stress/">stress</a>, <a href="/conditions/clinical-depression/">clinical depression</a>, <a href="/conditions/dementia/about-dementia/what-is-dementia/">dementia</a> and <a href="/conditions/alzheimers-disease/">Alzheimer's disease</a>.</p>
          <p>Given the overwhelming evidence, it seems obvious that we should all be physically active. It's essential if you want to live a healthy and fulfilling life into old age.</p><p>It's medically proven that people who do regular physical activity have lower risk of:</p><ul><li>coronary heart disease and stroke</li><li>type 2 diabetes</li><li><a href="/conditions/bowel-cancer/">bowel cancer</a></li><li><a href="/conditions/breast-cancer/">breast cancer in women</a></li><li>early death</li><li><a href="/conditions/osteoarthritis/">osteoarthritis</a></li><li><a href="/conditions/broken-hip/">hip fracture</a></li><li><a href="/conditions/falls/">falls</a> (among older adults)</li><li>depression</li><li>dementia</li></ul>
          <p>To stay healthy, the <a href="https://www.gov.uk/government/publications/physical-activity-guidelines-uk-chief-medical-officers-report">UK Chief Medical Officers' Physical Activity Guidelines, on GOV.UK</a>, state that adults should try to be active every day and aim to do at least 150 minutes of physical activity over a week, through a variety of activities.</p><p>For most people, the easiest way to get moving is to make activity part of everyday life, like <a href="/live-well/exercise/walking-for-health/">walking for health</a> or cycling instead of using the car to get around. However, the more you do, the better, and taking part in activities such as sports and exercise will make you even healthier.</p><p>For any type of activity to benefit your health, you need to be moving quick enough to raise your heart rate, breathe faster and feel warmer. This level of effort is called moderate intensity activity. If you're working at a moderate intensity you should still be able to talk but you won't be able to sing the words to a song.</p><p>An activity where you have to work even harder is called vigorous intensity activity. There is substantial evidence that vigorous activity can bring health benefits over and above that of moderate activity. You can tell when it's vigorous activity because you're breathing hard and fast, and your heart rate has gone up quite a bit. If you're working at this level, you won't be able to say more than a few words without pausing for a breath.</p>
          <p>People are less active nowadays, partly because technology has made our lives easier. We drive cars or take public transport. Machines wash our clothes. We entertain ourselves in front of a TV or computer screen. Fewer people are doing manual work, and most of us have jobs that involve little physical effort. Work, household chores, shopping and other necessary activities are far less demanding than for previous generations.</p><p>We move around less and burn off less energy than people used to. Research suggests that many adults spend more than 7 hours a day sitting down, at work, on transport or in their leisure time. People aged over 65 spend 10 hours or more each day sitting or lying down, making them the most sedentary age group.</p>
          <p>Inactivity is described by the Department of Health and Social Care as a "silent killer". Evidence is emerging that sedentary behaviour, such as sitting or lying down for long periods, is bad for your health.</p><p>Not only should you try to raise your activity levels, but you should also reduce the amount of time you and your family spend sitting down.</p><p>Common examples of sedentary behaviour include watching TV, using a computer, using the car for short journeys and sitting down to read, talk or listen to music. This type of behaviour is thought to increase your risk of developing many chronic diseases, such as heart disease, stroke and type 2 diabetes, as well as weight gain and <a href="/conditions/obesity/">obesity</a>.</p><p>Crucially, you can hit your weekly activity target but still be at risk of ill health if you spend the rest of the time sitting or lying down.</p><p>For a summary on the health benefits of being more active, check out these <a href="https://www.gov.uk/government/publications/physical-activity-guidelines-infographics">physical activity guidelines from the Department of Health and Social Care</a>.</p>
        </div>
    </div>
  );
}

export default BenefitsExerciseArticle;