import React from 'react';

function PhysicalActivities() {
  return (
    <div>
     <h1>Physical activity guidelines for adults aged 19 to 64</h1>
        <div>
          <p><b>Adults should do some type of physical activity every day. Exercise just once or twice a week can reduce the risk of heart disease or stroke.</b></p>
          <p>Speak to your GP first if you have not exercised for some time, or if you have medical conditions or concerns. Make sure your activity and its intensity are appropriate for your fitness.</p><p>Adults should aim to:</p><ul><li>do strengthening activities that work all the major muscle groups (legs, hips, back, abdomen, chest, shoulders and arms) on at least 2 days a week</li><li>do at least 150 minutes of moderate intensity activity a week or 75 minutes of vigorous intensity activity a week</li><li>spread exercise evenly over 4 to 5 days a week, or every day</li><li>reduce time spent sitting or lying down and break up long periods of not moving with some activity</li></ul><p>You can also achieve your weekly activity target with:</p><ul><li>several short sessions of very vigorous intensity activity</li><li>a mix of moderate, vigorous and very vigorous intensity activity</li></ul><p>These guidelines are also suitable for:</p><ul><li>disabled adults</li><li>pregnant women and new mothers</li></ul><p>When you start exercising after pregnancy, make sure your physical activity choices reflect your activity levels before pregnancy. You should include strength training.</p><p>After your 6- to 8-week postnatal check, you can start to do more intense activities if you feel you're able to. Vigorous activity is not recommended if you were inactive before pregnancy.</p>
          <p>Moderate activity will raise your heart rate, and make you breathe faster and feel warmer. One way to tell if you're working at a moderate intensity level is if you can still talk, but not sing.</p><p>Examples of moderate intensity activities include:</p><ul><li>brisk <a href="/live-well/exercise/walking-for-health/">walking</a></li><li>water aerobics</li><li>riding a bike</li><li>dancing</li><li>doubles tennis</li><li>pushing a lawn mower</li><li>hiking</li><li>rollerblading</li></ul>
          <p>Vigorous intensity activity makes you breathe hard and fast. If you're working at this level, you will not be able to say more than a few words without pausing for breath.</p><p>In general, 75 minutes of vigorous intensity activity a week can give similar health benefits to 150 minutes of moderate intensity activity.</p><p>Most moderate activities can become vigorous if you increase your effort.</p><p>Examples of vigorous activities include:</p><ul><li>running</li><li>swimming</li><li>riding a bike fast or on hills</li><li>walking up the stairs</li><li>sports, like football, rugby, netball and hockey</li><li>skipping</li><li>aerobics</li><li>gymnastics</li><li>martial arts</li></ul><p>For a moderate to vigorous workout, <a href="/live-well/exercise/get-running-with-couch-to-5k/">get running with Couch to 5K</a>, a 9-week running plan for beginners.</p>
          <p>Very vigorous activities are exercises performed in short bursts of maximum effort broken up with rest.</p><p>This type of exercise is also known as High Intensity Interval Training (HIIT).</p><p>Examples of very vigorous activities include:</p><ul><li>lifting heavy weights</li><li>circuit training</li><li>sprinting up hills</li><li>interval running</li><li>running up stairs</li><li>spinning classes</li></ul>
          <p>To get health benefits from strength exercises, you should do them to the point where you need a short rest before repeating the activity.</p><p>There are many ways you can strengthen your muscles, whether you're at home or in a gym.</p><p>Examples of muscle-strengthening activities include:</p><ul><li>carrying heavy shopping bags</li><li>yoga</li><li>pilates</li><li>tai chi</li><li>lifting weights</li><li>working with resistance bands</li><li>doing exercises that use your own body weight, such as push-ups and sit-ups</li><li>heavy gardening, such as digging and shovelling</li><li>wheeling a wheelchair</li><li>lifting and carrying children</li></ul><p>Try exercise routines like:</p><ul><li>strength workout videos in our <a href="/conditions/nhs-fitness-studio/">Fitness Studio exercise videos</a></li></ul><p>You can do activities that strengthen your muscles on the same or different days as your aerobic activity – whatever's best for you.</p><p>Muscle-strengthening exercises are not always an aerobic activity, so you'll need to do them as well as your 150 minutes of aerobic activity.</p>
          <ul><li><a href="/live-well/exercise/physical-activity-guidelines-children-under-five-years/">Physical activity guidelines for children (under 5 years)</a></li><li><a href="/live-well/exercise/physical-activity-guidelines-children-and-young-people/">Physical activity guidelines for children and young people</a></li><li><a href="/live-well/exercise/physical-activity-guidelines-older-adults/">Physical activity guidelines for older adults</a></li></ul><p>GOV.UK also has a number of <a href="https://www.gov.uk/government/publications/physical-activity-guidelines-infographics">physical activity guidelines as infographics</a>.</p>
        </div>
      </div>
  );
}

export default PhysicalActivities;
