import React from 'react';

function SittingArticle() {
  return (
    <div>
       <h1>Why we should sit less</h1>
        <div>
          <p><b>There is increasing evidence that, unless you are a wheelchair user, sitting down too much can be a risk to your health</b></p><p>To reduce our risk of ill health from inactivity, we are advised to exercise regularly, at least <a href="/live-well/exercise/physical-activity-guidelines-for-adults-aged-19-to-64/">150 minutes a week</a>, and reduce sitting time.</p><p>Studies have linked being inactive with being overweight and obese, <a href="/conditions/type-2-diabetes/">type 2 diabetes</a>, some types of <a href="/conditions/cancer/">cancer</a>, and early death.</p><p>Sitting for long periods is thought to slow the metabolism, which affects the body's ability to regulate blood sugar, blood pressure and break down body fat.</p><p>Many adults in the UK spend around 9 hours a day sitting. This includes watching TV, using a computer, reading, doing homework, travelling by car, bus or train but does not include sleeping.</p>
          <p>The <a href="https://www.gov.uk/government/publications/physical-activity-guidelines-uk-chief-medical-officers-report">UK Chief Medical Officers' Physical Activity Guidelines report on GOV.UK</a> recommends breaking up long periods of sitting time with at least light activity.</p><p>However, there is currently not enough evidence to set a time limit on how much time people should sit each day.</p><p>Nevertheless, some countries – such as Australia – have made recommendations that children limit screen time, such as TV and video games, to 1 to 2 hours a day. This is to reduce the time spent sitting.</p>
          <p>The link between illness and sitting first emerged in the 1950s, when researchers found double decker bus drivers were twice as likely to have heart attacks as their bus conductor colleagues. The drivers sat for 90 per cent of their shifts, the conductors climbed about 600 stairs each working day.</p><p>It is thought excessive sitting slows the metabolism – which affects our ability to regulate blood sugar and blood pressure, and metabolise fat – and may cause weaker muscles and bones.</p><p>Research on astronauts in the early 1970s found life in zero gravity was linked with accelerated bone and muscle loss and ageing.</p>
          <p>Most of the evidence is based on observational studies, which have only shown an association between sitting and ill health but not a direct cause.</p>
          <p>In children under 5, the advice is to limit the time they spend watching TV, travelling by car, bus or train, or being strapped into a buggy.</p><p>While this may be a challenge for busy parents, the advice reflects growing awareness that early life experiences and habits impact upon our health as adults.</p><p>Tips to reduce sitting time:</p><ul><li>do not leave a child in a pram or buggy, car seats or highchair for longer than 1 hour at a time</li><li>reduce time spent in walking aids or baby bouncers</li><li>reduce time spent in front of the TV or other screens</li></ul><p><a href="/live-well/exercise/physical-activity-guidelines-children-under-five-years/">Find out about physical activity guidelines for children under 5 years</a></p>
          <p>For children and teenagers aged 5 to 18, reducing sitting time includes anything that involves moving in and around the home, classroom or community.</p><p>Tips to reduce sitting time:</p><ul><li>consider ways for children and teenagers to "earn" screen time</li><li>agree a family limit to screen time per day</li><li>make bedrooms a TV, electronic device, laptop and phone-free zone</li><li>set "no screen time" rules to encourage other activities</li><li>encourage participation in house chores, such as setting the table or taking the bins out</li><li>choose gifts such as a scooter, skateboard, ball or kite to encourage active play</li></ul><p>Parents could lead by example by also reducing their TV time and other sitting-based tasks.</p><p><a href="/live-well/exercise/physical-activity-guidelines-children-and-young-people/">Find out about physical activity guidelines for children and young people</a></p>
          <p>Adults aged 19 to 64 are advised to try to sit down less throughout the day, including at work, when travelling and at home.</p><p>Tips to reduce sitting time:</p><ul><li>stand on the train or bus</li><li>take the stairs and walk up escalators</li><li>set a reminder to get up every 30 minutes</li><li>place a laptop on a box or similar to work standing</li><li>stand or walk around while on the phone</li><li>take a walk break every time you take a coffee or tea break</li><li>walk to a colleague's desk instead of emailing or calling</li><li>swap some TV time for more active tasks or hobbies</li></ul><p><a href="/live-well/exercise/physical-activity-guidelines-for-adults-aged-19-to-64/">Find out about physical activity guidelines for adults aged 19 to 64</a></p>
          <p>Some older people (aged 65 and over) are known to spend 9 hours or more each day sitting.</p><p>Tips to reduce sitting time:</p><ul><li>avoid long periods sat in front of a TV or computer</li><li>stand up and move during TV advert breaks</li><li>stand or walk while on the phone</li><li>use the stairs as much as possible</li><li>take up active hobbies such as gardening and DIY</li><li>join in community-based activities, such as dance classes and walking groups</li><li>take up active play with grandchildren, if you have them</li><li>do most types of housework</li></ul><p><a href="/live-well/exercise/physical-activity-guidelines-older-adults/">Find out about physical activity guidelines for older adults</a></p>
        </div>
    </div>
  );
}

export default SittingArticle;