import React from 'react';

function StressArticle() {
  return (
    <div id='stress'>
      <h1>Stress</h1>
      <p><b>Most people feel stressed sometimes and some people find stress helpful or even motivating. But if stress is affecting your life, there are things you can try that may help.</b></p><p>Support is also available if you're finding it hard to cope with stress.</p>
      <p>Stress can cause many different symptoms. It might affect how you feel physically, mentally and also how you behave.</p><p>It's not always easy to recognise when stress is the reason you're feeling or acting differently.</p>
      <h3>Referring yourself for therapy</h3><p>If you need more support, you can get free talking therapies like <a href="/mental-health/talking-therapies-medicine-treatments/talking-therapies-and-counselling/cognitive-behavioural-therapy-cbt/overview/">cognitive behavioural therapy (CBT)</a> on the NHS.</p><p>You can refer yourself directly to an NHS talking therapies service without a referral from a GP.</p>
      <h3>See a GP if:</h3><div class="block-richtext"> <ul><li>you're struggling to cope with stress</li><li>things you're trying yourself are not helping</li><li>you would prefer to get a referral from a GP</li></ul> </div>
      <h3>Call 111 or ask for an urgent GP appointment if:</h3><div class="block-richtext"> <ul><li>you need help urgently, but it's not an emergency</li></ul><p>111 can tell you the right place to get help if you need to see someone. Go to <a href="https://111.nhs.uk">111.nhs.uk</a> or <a href="Tel: 111">call: 111</a>.</p> </div>
      <h3>Call 999 or go to A&amp;E now if:</h3><div class="block-richtext"> <ul><li>you or someone you know needs immediate help</li><li>you have seriously harmed yourself – for example, by taking a drug overdose</li></ul><p>A mental health emergency should be taken as seriously as a medical emergency.</p><p><a href="https://www.nhs.uk/Service-Search/Accident-and-emergency-services/LocationSearch/428">Find your nearest A&amp;E</a></p> </div>
      <p>Stress is usually a reaction to mental or emotional pressure. It's often related to feeling like you're losing control over something, but sometimes there's no obvious cause.</p><p>When you're feeling anxious or scared, your body releases stress hormones such as adrenaline and cortisol.</p><p>This can be helpful for some people and stress might help you get things done or feel more motivated.</p><p>But it might also cause physical symptoms such as a faster heartbeat or sweating. If you're stressed all the time it can become a problem.</p><h3>Identifying the cause</h3><p>If you know what's causing your stress it might be easier to find ways to manage it.</p><p>Some examples of things that may cause stress include:</p><ul><li>work – feeling pressure at work, unemployment or retirement</li><li>family – relationship difficulties, divorce or <a href="/conditions/social-care-and-support-guide/support-and-benefits-for-carers/">caring for someone</a></li><li>financial problems – unexpected bills or borrowing money</li><li>health – illness, injury or <a href="/mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/grief-bereavement-loss/">losing someone (bereavement)</a></li></ul><p>Even significant life events such as buying a house, having a baby or planning a wedding could lead to feelings of stress.</p><p>You might find it hard to explain to people why you feel this way, but talking to someone could help you find a solution.</p><p><a href="/mental-health/self-help/guides-tools-and-activities/five-steps-to-mental-wellbeing/">Find out about the 5 steps to mental wellbeing</a></p>
    </div>
  );
}
export default StressArticle;