import React from 'react';

function TipsArticle() {
  return (
    <div>
       <h1>8 tips for healthy eating</h1>
        <div>
          <p>These 8 practical tips cover the basics of healthy eating and can help you make healthier choices.</p><p>The key to a healthy diet is to eat the right amount of calories for how active you are so you balance the energy you consume with the energy you use.</p><p>If you eat or drink more than your body needs, you'll put on weight because the energy you do not use is stored as fat. If you eat and drink too little, you'll lose weight.</p><p>You should also eat a wide range of foods to make sure you're getting a balanced diet and your body is receiving all the nutrients it needs.</p><p>It's recommended that men have around 2,500 calories a day (10,500 kilojoules). Women should have around 2,000 calories a day (8,400 kilojoules).</p><p>Most adults in the UK are eating more calories than they need and should eat fewer calories.</p>
          <p><a href="/live-well/eat-well/food-types/starchy-foods-and-carbohydrates/">Starchy carbohydrates</a> should make up just over a third of the food you eat. They include potatoes, bread, rice, pasta and cereals.</p><p>Choose higher fibre or wholegrain varieties, such as wholewheat pasta, brown rice or potatoes with their skins on.</p><p>They contain more fibre than white or refined starchy carbohydrates and can help you feel full for longer.</p><p>Try to include at least 1 starchy food with each main meal. Some people think starchy foods are fattening, but gram for gram the carbohydrate they contain provides fewer than half the calories of fat.</p><p>Keep an eye on the fats you add when you're cooking or serving these types of foods because that's what increases the calorie content – for example, oil on chips, butter on bread and creamy sauces on pasta.</p>
          <p>It's recommended that you eat at least 5 portions of a variety of fruit and veg every day. They can be fresh, frozen, canned, dried or juiced.</p><p>Getting your <a href="/live-well/eat-well/5-a-day/">5 A Day</a> is easier than it sounds. Why not chop a banana over your breakfast cereal, or swap your usual mid-morning snack for a piece of fresh fruit?</p><p>A portion of fresh, canned or frozen fruit and vegetables is 80g. A portion of dried fruit (which should be kept to mealtimes) is 30g.</p><p>A 150ml glass of fruit juice, vegetable juice or smoothie also counts as 1 portion, but limit the amount you have to no more than 1 glass a day as these drinks are sugary and can damage your teeth.</p>
          <p>Fish is a good source of protein and contains many <a href="/conditions/vitamins-and-minerals/">vitamins and minerals</a>.</p><p>Aim to eat at least 2 portions of fish a week, including at least 1 portion of oily fish.</p><p>Oily fish are high in omega-3 fats, which may help prevent heart disease. </p><p>Oily fish include:</p><ul><li>salmon</li><li>trout</li><li>herring</li><li>sardines</li><li>pilchards</li><li>mackerel</li></ul><p>Non-oily fish include:</p><ul><li>haddock</li><li>plaice</li><li>coley</li><li>cod</li><li>tuna</li><li>skate</li><li>hake</li></ul><p>You can choose from fresh, frozen and canned, but remember that canned and smoked fish can be high in salt.</p><p>Most people should be eating more fish, but there are recommended limits for some types of fish.</p><p><a href="/live-well/eat-well/food-types/fish-and-shellfish-nutrition/">Find out more about fish and shellfish</a></p>
          <p>You need some fat in your diet, but it's important to pay attention to the amount and type of fat you're eating.</p><p>There are 2 main types of fat: saturated and unsaturated. Too much saturated fat can increase the amount of cholesterol in the blood, which increases your risk of developing heart disease.</p><p>On average, men should have no more than 30g of saturated fat a day. On average, women should have no more than 20g of saturated fat a day.</p><p>Children under the age of 11 should have less saturated fat than adults, but a low-fat diet is not suitable for children under 5.</p><p>Saturated fat is found in many foods, such as:</p><ul><li>fatty cuts of meat</li><li>sausages</li><li>butter</li><li>hard cheese</li><li>cream</li><li>cakes</li><li>biscuits</li><li>lard</li><li>pies</li></ul><p>Try to <a href="/live-well/eat-well/how-to-eat-a-balanced-diet/eat-less-saturated-fat/">eat less saturated fat</a> and choose foods that contain unsaturated fats instead, such as vegetable oils and spreads, oily fish and avocados.</p><p>For a healthier choice, use a small amount of vegetable or olive oil, or reduced-fat spread instead of butter, lard or ghee.</p><p>When you're having meat, choose lean cuts and cut off any visible fat.</p><p>All types of fat are high in energy, so they should only be eaten in small amounts.</p><h3>Sugar</h3><p>Regularly consuming foods and drinks high in <a href="/live-well/eat-well/food-types/how-does-sugar-in-our-diet-affect-our-health/">sugar</a> increases your risk of <a href="/conditions/obesity/">obesity</a> and <a href="/conditions/tooth-decay/">tooth decay</a>.</p><p>Sugary foods and drinks are often high in energy (measured in kilojoules or calories), and if consumed too often can contribute to weight gain. They can also cause tooth decay, especially if eaten between meals.</p><p>Free sugars are any sugars added to foods or drinks, or found naturally in honey, syrups and unsweetened fruit juices and smoothies.</p><p>This is the type of sugar you should be cutting down on, rather than the sugar found in fruit and milk.</p><p>Many packaged foods and drinks contain surprisingly high amounts of free sugars.</p><p>Free sugars are found in many foods, such as:</p><ul><li>sugary fizzy drinks</li><li>sugary breakfast cereals</li><li>cakes</li><li>biscuits</li><li>pastries and puddings</li><li>sweets and chocolate</li><li>alcoholic drinks</li></ul><p><a href="/live-well/eat-well/food-guidelines-and-food-labels/how-to-read-food-labels/">Food labels</a> can help. Use them to check how much sugar foods contain.</p><p>More than 22.5g of total sugars per 100g means the food is high in sugar, while 5g of total sugars or less per 100g means the food is low in sugar.</p><p><a href="/live-well/eat-well/how-to-eat-a-balanced-diet/how-to-cut-down-on-sugar-in-your-diet/">Find out how to cut down on sugar in your diet</a></p>
          <p>Eating too much salt can raise your blood pressure. People with <a href="/conditions/high-blood-pressure-hypertension/">high blood pressure</a> are more likely to develop heart disease or have a stroke.</p><p>Even if you do not add salt to your food, you may still be eating too much.</p><p>About three-quarters of the salt you eat is already in the food when you buy it, such as breakfast cereals, soups, breads and sauces.</p><p>Use food labels to help you cut down. More than 1.5g of salt per 100g means the food is high in salt.</p><p>Adults and children aged 11 and over should eat no more than 6g of salt (about a teaspoonful) a day. Younger children should have even less.</p><p><a href="/live-well/eat-well/how-to-eat-a-balanced-diet/tips-for-a-lower-salt-diet/">Get tips for a lower salt diet</a></p>
          <p>As well as eating healthily, regular exercise may help reduce your risk of getting serious health conditions. It's also important for your overall health and wellbeing.</p><p>Read more about the <a href="/live-well/exercise/exercise-health-benefits/">benefits of exercise</a> and <a href="/live-well/exercise/physical-activity-guidelines-for-adults-aged-19-to-64/">physical activity guidelines for adults</a>.</p><p>Being overweight or obese can lead to health conditions, such as type 2 diabetes, certain cancers, heart disease and stroke. Being underweight could also affect your health.</p><p>Most adults need to lose weight by eating fewer calories.</p><p>If you're trying to lose weight, aim to eat less and be more active. Eating a healthy, balanced diet can help you maintain a healthy weight.</p><p>Check whether you're a healthy weight by using the <a href="/live-well/healthy-weight/bmi-calculator/">BMI healthy weight calculator</a>.</p><p><a href="https://www.nhs.uk/better-health/lose-weight/">Lose weight with the NHS weight loss plan</a>, a 12-week weight loss guide that combines advice on healthier eating and physical activity.</p><p>If you're underweight, see <a href="/live-well/healthy-weight/managing-your-weight/healthy-ways-to-gain-weight/">underweight adults</a>. If you're worried about your weight, ask your GP or a dietitian for advice.</p>
          <p>You need to drink plenty of fluids to stop you getting dehydrated. The government recommends drinking 6 to 8 glasses every day. This is in addition to the fluid you get from the food you eat. </p><p>All non-alcoholic drinks count, but water, lower fat milk and lower sugar drinks, including tea and coffee, are healthier choices. </p><p>Try to avoid sugary soft and fizzy drinks, as they're high in calories. They're also bad for your teeth. </p><p>Even unsweetened fruit juice and smoothies are high in free sugar.</p><p>Your combined total of drinks from fruit juice, vegetable juice and smoothies should not be more than 150ml a day, which is a small glass.</p><p>Remember to drink more fluids during hot weather or while exercising.</p>
          <p>Some people skip breakfast because they think it'll help them lose weight.</p><p>But a healthy breakfast high in fibre and low in fat, sugar and salt can form part of a balanced diet, and can help you get the nutrients you need for good health.</p><p>A wholegrain lower sugar cereal with semi-skimmed milk and fruit sliced over the top is a tasty and healthier breakfast.</p>
          <ul><li>The <a href="/live-well/eat-well/food-guidelines-and-food-labels/the-eatwell-guide/">Eatwell Guide</a> can help you get the right balance of the 5 main food groups. The guide shows you how much of what you eat should come from each food group.</li><li>Read more about <a href="/live-well/eat-well/how-to-eat-a-balanced-diet/eating-a-balanced-diet/">eating a balanced diet</a> and <a href="/live-well/healthy-weight/managing-your-weight/understanding-calories/">understanding calories</a>.</li></ul>
        </div>
    </div>
  );
}

export default TipsArticle;