# Generated by Django 5.0.2 on 2024-03-30 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_receiver_alter_message_sender_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='mhp_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='employee',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='mhp',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, related_name='mhp_id', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=57, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
