# Generated by Django 5.0.2 on 2024-04-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chat_employee_id_remove_chat_mhp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message_at',
            field=models.DateTimeField(),
        ),
    ]
