# Generated by Django 5.0.2 on 2024-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_title',
            field=models.TextField(),
        ),
    ]
