# Generated by Django 5.0.3 on 2024-04-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='posted_at',
        ),
    ]
