# Generated by Django 5.0.3 on 2024-04-04 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_posts_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
